### ISSUE TITLE
How to ignore validating while parsing for differences

### ISSUE THREAD

**Issue by dieterbaier** [xmlunit/user-guide#4] opened 2016-04-12 16:29 UTC
I use the DiffBuilder to compare two XML-Sources. The Sources do have a Doctype-Declaration at the beginning.

Is there any possibility to tell the DiffBuilder not to ignore any Schema-References, nor it should not validate any XMLs?

Thanks

Dieter

P.S.: using XMLUnit 2.1.1

**Comment by bodewig** [comment] 2016-04-13 11:13
Duplicate of https://github.com/xmlunit/xmlunit/issues/82

**Closed as completed by bodewig** 2016-04-13 11:13 UTC
